services:
  n8n:
    image: 'n8nio/n8n:1.115.2'
    networks:
      - coolify
    environment:
      # --- Variáveis Adicionadas/Corrigidas para o Main Process ---
      # CRÍTICO: Define este contêiner como o processo Main (gerencia Webhooks e UI)
      - N8N_EXECUTION_PROCESS=main 
      
      # --- Variáveis de Conexão e URL ---
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      
      # --- Variáveis de Banco de Dados ---
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_PORT=5432
      - 'DB_POSTGRESDB_HOST=${POSTGRES_CONTAINER_NAME}'
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - 'DB_POSTGRESDB_PASSWORD=${POSTGRES_PW}'
      - N8N_ENCRYPTION_KEY=YOURENCRYPTIONKEY # -- TROCAR POR KEY 256 bytes
      
      # --- Variáveis de Fila (Redis) ---
      - 'QUEUE_BULL_REDIS_HOST=${REDIS_CONTAINER_NAME}'
      - 'QUEUE_BULL_REDIS_PASSWORD=${REDIS_PW}'
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      
      # --- Variáveis de Segurança/Proxy ---
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_SECURE_COOKIE=true
      - N8N_TRUSTED_PROXIES=${N8N_TRUSTED_PROXIES}
      - N8N_PROXY_HOPS=1
      
      # --- Variáveis de Execução (Ajustadas) ---
      - EXECUTIONS_MODE=queue
      # REMOVIDO: N8N_RUNNERS_ENABLED=true (O Main não deve ser um Runner na arquitetura Worker/Main)
      # REMOVIDO: N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true (Está depreciada. N8N_EXECUTION_PROCESS=main resolve o problema de sobreposição.)
      
    volumes:
      - 'n8n-data:/home/node/.n8n'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
networks:
  coolify:
    driver: bridge